version: '3'
services:
  sqlite:
    image: "nouchka/sqlite3"
    restart: always
  backend:
    container_name: backend
    build: ./node-backend/
    restart: always
    ports:
      - "6200:6200"
    volumes:
      - ./node-backend:/usr/src/app
    depends_on:
      - sqlite
  frontend:
    container_name: frontend
    build: ./react-frontend/
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend:/usr/src/app
    depends_on:
      - backend